### ISSUE TITLE
wcs 2.0.1 te2 Test wcs2:req41 has problem

### ISSUE THREAD

**Issue by greatzzk** [opengeospatial/ets-wcs20#124] opened 2023-08-02 21:16 UTC
error msg from test:
![image](https://github.com/opengeospatial/ets-wcs20/assets/11200872/cb2b3de8-ea60-4e42-ab8e-e25302e6e4fc)
![image](https://github.com/opengeospatial/ets-wcs20/assets/11200872/df0f2ebd-4787-4ed6-ae28-ca47ab3f65fc)

but i think my server has the correct response containing an "invalidAxisLabel" exception.
http://54.90.187.123:6080/arcgis/services/mynetcdf/ImageServer/WCSServer?&request=GetCoverage&coverageid=mynetcdf&service=WCS&VERSION=2.0.1&subset=fakeaxislabel(10)
![image](https://github.com/opengeospatial/ets-wcs20/assets/11200872/ad74c072-255e-40fd-9994-7e92a4026f2c)

could you help investigate?

**Comment by bpross-52n** [comment] 2023-08-03 08:14
Hi @greatzzk, we noticed that the server responds a HTTP 404 error with no body, if we execute the request in your comment above. Could you have a look into that?

**Comment by greatzzk** [comment] 2023-08-03 22:23
@bpross-52n i am not sure if i understand your comment. isn't the response displaying in screenshot above showing it is inside "body" of the response?

**Comment by bpross-52n** [comment] 2023-08-04 07:05
@greatzzk You are right, sorry. I only opened the [URL](http://54.90.187.123:6080/arcgis/services/mynetcdf/ImageServer/WCSServer?&request=GetCoverage&coverageid=mynetcdf&service=WCS&VERSION=2.0.1&subset=fakeaxislabel(10)) in the browser and there no body was shown, only a browser error page. With more advanced tools the body is shown. Sorry for the confusion.

**Comment by bpross-52n** [comment] 2023-08-04 09:42
@greatzzk The problem is that the test suite is only looking for Envelope-Elements in the CoverageDescription and your service has EnvelopWithTimePeriod, which is fine, of course. So I think this is a bug in the test suite. I will work on a solution.

**Comment by bpross-52n** [comment] 2023-08-04 13:55
My current findings are:
The failing test (see the code [here](https://github.com/opengeospatial/ets-wcs20/blob/5df7d948f516077f6716e89ea39744b8fd7acfe5/src/main/scripts/ctl/GetCoverage.xml#L2069)) sends the following request: 
`http://54.90.187.123:6080/arcgis/services/mynetcdf/ImageServer/WCSServer?service=WCS&VERSION=2.0.1&request=GetCoverage&coverageid=mynetcdf&subset=x(-1.67048810872E7)&subset=x(-1.67048810872E7,-1.67048810872E7)`

Response:
````
<ows:ExceptionReport
	xmlns:ows="http://www.opengis.net/ows/2.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="2.0.0"
	xsi:schemaLocation="http://www.opengis.net/ows/2.0 http://schemas.opengis.net/ows/2.0/owsExceptionReport.xsd">
	<ows:Exception exceptionCode="InvalidSubsetting"
		locator="(-1.67048810872E7,-1.67048810872E7)" />
</ows:ExceptionReport>
````
Other services return an InvalidAxisLabel exception code here, because of the duplicate x-axis, thus pasing the test. We will confirm that this is the correct behavior.

**Comment by dstenger** [comment] 2023-08-10 08:24
Requirement 41 is specified in this document https://portal.opengeospatial.org/files/?artifact_id=48428.
@bpross-52n Can you please check whether InvalidAxisLabel **and** InvalidSubsetting are correct in this case and adjust the test accordingly?

**Comment by bpross-52n** [comment] 2023-08-18 09:14
The test was modified now so that a valid subsetting request is created (first axis with correct values, second axis with correct values) and then a duplicate of the first axis with correct values is appended to the request. This leads now to the expexted exception code InvalidAxisLabel. An InvalidSubsetting exception should not be returned anymore, because the subsetting is correct. I tested with the service referenced here.

**Closed** 2023-08-22 17:21 UTC
Labels: bug

**Comment by greatzzk** [comment] 2023-10-03 00:07
i verified this issue on te2 against my server. cheers!!
