### ISSUE TITLE
Why is wcs2:get-scal-req3-kvp failing?

### ISSUE THREAD

**Issue by pomakis** [opengeospatial/ets-wcs20#83] opened 2019-07-05 19:44 UTC
I'm trying to run "https://onestop.cubewerx.com/cubewerx/citeWcs201.cgi" through the Web Coverage Service (WCS) 2.0.1 CITE tests (version 1.12), and one of the tests it's failing is "wcs2:get-scal-req3-kvp", which tests the requirement:

Requirement 3 grid-coverage:
The coverage identifier in a GetCoverage request shall address a coverage which is a GridCoverage, RectifiedGridCoverage, ReferenceableGridCoverage, or a subtype of one of these.

I guess what it's really testing at this point is whether or not any such coverages exist so that this test can be performed.

The Contents section in the capabilities document of the abovementioned WCS 2.0.1 server is:

```
  <Contents>
    <CoverageSummary>
      <ows:WGS84BoundingBox>
        <ows:LowerCorner>-179.9833333333333 -89.98333333333333</ows:LowerCorner>
        <ows:UpperCorner>179.9833333333333 89.98333333333333</ows:UpperCorner>
      </ows:WGS84BoundingBox>
      <CoverageId>etopo2</CoverageId>
      <CoverageSubtype>RectifiedGridCoverage</CoverageSubtype>
    </CoverageSummary>
    <CoverageSummary>
      <ows:WGS84BoundingBox>
        <ows:LowerCorner>-179.9958333333333 -89.99583333332134</ows:LowerCorner>
        <ows:UpperCorner>179.9958333333173 89.99583333333334</ows:UpperCorner>
      </ows:WGS84BoundingBox>
      <CoverageId>gtopo30</CoverageId>
      <CoverageSubtype>RectifiedGridCoverage</CoverageSubtype>
    </CoverageSummary>
  </Contents>
```
It's clear that both of the availaboe coverages are "RectifiedGridCoverage"s.  Yet this test fails, indicating:

Message d1506e639_1:
   [FAILURE] The service should offer at least one GridCoverage.

Message d1506e703_1:
   [MESSAGE] The server does not support the gml coverage.

Message d1506e783_1:
   [FAILURE] The service should offer at least one ReferenceableGridCoverage.

Why is this?  Is this an issue with the test, or with the way this server declares its contents?

**Comment by dstenger** [comment] 2019-07-08 08:30
Thank you for reporting. We will do further investigation.

**Comment by keshav-nangare** [comment] 2019-07-08 15:56
I went through the test implementation and got the reason for failure. As per the current implementation of the test: `wcs2:get-scal-req3-kvp` it expects the `GridCoverage` in the capability i.e reason of test failure. Below are the references: 

https://github.com/opengeospatial/ets-wcs20/blob/80031ab5ef7233b58468ba1977b40e62bcc0b30c/src/main/scripts/ctl/ext_get-scal.xml#L35-L48


https://github.com/opengeospatial/ets-wcs20/blob/80031ab5ef7233b58468ba1977b40e62bcc0b30c/src/main/scripts/ctl/ext_get-scal.xml#L313-L320


We can see the test `wcs2:get-scal-req3-kvp implementation clearly, if the `GridCoverageId` is not found then test get failed because the capability document does not have the `GridCoverage`.

But according to comment: 

> Requirement 3 grid-coverage:
> The coverage identifier in a GetCoverage request shall address a coverage which is a GridCoverage, > > RectifiedGridCoverage, ReferenceableGridCoverage, or a subtype of one of these.

The test should expect any one of them and continue further execution.

 @dstenger  What should we do in this case? Should we update the test implementation?

**Comment by lgoltz** [comment] 2019-07-15 05:53
As far as I see this issue is related to #37

**Comment by lgoltz** [comment] 2019-07-31 06:48
@pomakis Can you check if this issue is a duplicate of #37?

**Comment by pomakis** [comment] 2019-07-31 18:59
I'm not familiar enough with the nuances of #37 to know whether or not it's the same bug as this, but it's certainly related.  All I know is that RectifiedGridCoverage should be a valid CoverageSubtype for this test, yet it's rejected.

**Comment by ghobona** [comment] 2023-06-22 09:15
@pomakis Is this Issue still valid?

If so, could you please provide a link to a service so that we can reproduce the issue?

**Closed** 2024-02-23 15:22 UTC
Labels: question, status:waiting
